config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :exercises
  end
  root 'workouts#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))

		redirect_to workout_path(@workout)
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :find_workout, only: [:show, :edit, :update, :destroy]

	def index
		@workouts = Workout.all.order("created_at DESC")
	end


	def show
	end

	def new
		@workout = Workout.new
	end

	def create
		@workout = Workout.new(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def update
		if @workout.update(workout_params)
			 redirect_to @workout
		else
			 render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end

private

	def workout_params
		params.require(:workout).permit(:date, :workout, :mood, :length)
	end

	def find_workout
		@workout = Workout.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<p><%= exercise.name %></p>
<p><%= exercise.sets %></p>
<p><%= exercise.reps %></p>

app/views/exercises/_form.html.erb
<%= simple_form_for([@workout, @workout.exercises.build]) do |f| %>

	<%= f.input :name, input_html: { class: "form-control" } %>
	<%= f.input :sets, input_html: { class: "form-control" } %>
	<%= f.input :reps, input_html: { class: "form-control" } %>

	<br/>

	<%= f.button :submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Workout Log", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <%= link_to "New Workout", new_workout_path, class: "navbar navbar-link" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Log 2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: { class: 'form-horizontal'}) do |f| %>
	<%= f.input :date, label: "Date" %>
	<%= f.input :workout, label: "What area did you workout?", input_html: { class: "form-control" } %>
	<%= f.input :mood, label: "How were you feeling?", input_html: { class: "form-control"} %>
	<%= f.input :length, label: "How long was the workout?", input_html: { class: "form-control" } %>
	<br/>
	<%= f.button :submit %>
<% end %>

app/views/workouts/edit.html.erb
<h1> Edit Workout </h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/workouts/index.html.erb
<div id="index_workouts">
	<% @workouts.each do |workout| %>
	<h2><%= link_to workout.date.strftime("%A %B %d"), workout %></h2>
	<h3><span>Workout:</span>
		<%= workout.workout %>
	</h3>
	<% end %>
</div>

app/views/workouts/new.html.erb
<h1> New Workout </h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/workouts/show.html.erb
<div id="workout">
	<p><%= @workout.date %></p>
	<p><%= @workout.workout %></p>
	<p><%= @workout.mood %></p>
	<p><%= @workout.length %></p>
</div>

<div id="exercises">
	<h2>Exercises</h2>
		<%= render @workout.exercises %>
	<h3> Add an exercise </h3>
		<%= render "exercises/form" %>
</div>

<%= link_to "Back", root_path %> |
<%= link_to "Edit", edit_workout_path(@workout) %> |
<%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are You Sure"} %>